# Generated by Django 4.0.2 on 2022-03-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_newsfeed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
